### ISSUE TITLE
Fresnel for plastic is missing

### ISSUE THREAD

**Issue by frame-r** [phgphg777/DXR-PathTracer#1]
In main shader the followeng lines were occured:
float3 spec = ((D * G) / (4 * IN * ON));
Why F is not participated in this equation?

**Comment by phgphg777** [comment]
As you know, the usual DFG term is originated from the microfacet theory for metal. Microfacet theory is a kind of complete theory based on the assumption that every incident light on a surface is reflected or absorbed. For the dielectric such as plastic, however, we must consider the effect of transmitted light and their scattering in volumes. In Graphics, unfortunately, there are no brdf models for general dielectric except for ideal dielectric such as glass. So, almost graphics application simply use a linear combination of Lambertian and some metal model for plastic :
	f_plastic = (1-r)*f_lamertian + r*f_metal.
However, there is a fatal drawback to this linear combination model. From now on, I assume the roughness of a surface closes to 0 for the simple explanation. Whether plastic or metal, if lights enter at grazing angle on a flat surface every portion of it must be perfectly reflected due to the Fresnel effect. Thus, 1 = f_plastic = f_metal at grazing angle. As a result, if you model a brdf of plastic as a linear combination and you want to visualize the physically correct Fresnel effect you must set the constant of linear combination to be 1. This is a kind of contradiction.

More complex models resolving this problem is the one varying weights for Lambertian and metal term depending on incident angles. To see more detail, you should read the following papers:
	1. A Microfacet-based BRDF Generator (See section 5.1)
	2. Physically-Based Shading at Disney
In my opinion, however, calculating weights in these papers does not involve any physical consideration and their approximation of energy conservation is somewhat rough.

I also have no good idea of modeling brdf for plastic, I just choose the linear combination model but exclude the non-sense F term in plastic. Actually, unlike the case of metals, it is difficult to be aware of F term in the visualization. So, whether you include F or not is a matter of preference.

**Comment by frame-r** [comment]
Thank for answer!
Original Disney wasn't energy conserving, but Frostbyte tried normalize diffuse term (https://seblagarde.files.wordpress.com/2015/07/course_notes_moving_frostbite_to_pbr_v32 3.1.3)
Also in pbrt has Ashikhmin and Shirley’s diffuse equation that conserves energy (http://www.pbr-book.org/3ed-2018/Reflection_Models/Fresnel_Incidence_Effects.html).
